options:
  auto-update: true
drugs:
  cocaine:
    effects-duration: #in integer number, so it will be multiplied by 20 ticks in the code (20 ticks = 1 second)
      night-vision: 60 #default: 60
      speed: 10 #default: 10
      nausea: 10 #default: 10
      strength: 10 #default: 10
      regeneration: 10 #default: 10
    power-duration: #in integer number
      night-vision: 1 #default: 1
      speed: 2 #default: 2
      nausea: 2 #default: 2
      strength: 3 #default: 3
      regeneration: 1 #default: 1